# .github/workflows/build.yml
#
# ZMKファームウェアのビルドを定義するGitHub Actionsワークフロー
# YAML構文エラーを修正したバージョンです。

name: 'Build ZMK Firmware'

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # ZMK公式のビルドワークフローを再利用する
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    # ビルドワークフローに渡すパラメータ
    with:
      # 'matrix' に渡す値を、'|' を使って複数行の文字列として定義します。
      # これにより、後続の 'include:' が正しく解釈されます。
      matrix: |
        include:
          # 左手用のビルド設定
          - board: seeed_xiao_nrf52840
            shield: at_ease_keys_04_left
          # 右手用のビルド設定
          - board: seeed_xiao_nrf52840
            shield: at_ease_keys_04_right
