# .github/workflows/build.yml
#
# ZMKファームウェアのビルドを定義するGitHub Actionsワークフロー
# 正しい strategy/matrix 構文で修正したバージョンです。

name: 'Build ZMK Firmware'

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # GitHub Actionsの標準機能で、ビルドの組み合わせを定義
    strategy:
      # ビルドが一つ失敗しても、他のビルドは継続する
      fail-fast: false
      matrix:
        # include リスト内にビルドしたい board と shield のペアを記述
        include:
          # 左手用のビルド設定
          - board: seeed_xiao_nrf52840
            shield: at_ease_keys_04_left
          # 右手用のビルド設定
          - board: seeed_xiao_nrf52840
            shield: at_ease_keys_04_right

    # ZMK公式のビルドワークフローを再利用する
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    # ビルドワークフローに渡すパラメータ
    with:
      # matrixで定義した値を、入力として渡す
      board: ${{ matrix.board }}
      shield: ${{ matrix.shield }}
